import os
import re
import shutil

# --- Configuration ---
# 1. Path to your folder containing all the images (original + augmented)
DATASET_PATH = 'C:\\Users\\Admin\\\Desktop\\images2'

# 2. Name of the folder where augmented files will be moved for review
REVIEW_FOLDER_NAME ='C:\\Users\\Admin\\Desktop\\new_images2'

# 3. Common keywords used by augmentation tools. Add more if needed!
AUGMENTATION_KEYWORDS = [
    'rotate', 'rot', 'flip', 'shear', 'crop', 'zoom', 'bright', 'hue', 'sat',
    'noise', 'gamma', 'blur', 'gauss', 'scale', 'translate',
]

# Regular expression to match long random hashes often generated by augmentors
# This matches a pattern like '_1a3b5c7d_' or similar alphanumeric strings
HASH_PATTERN = re.compile(r'[a-zA-Z0-9]{8,15}')

# --- Execution ---

# Create the review folder
review_path = os.path.join(DATASET_PATH, REVIEW_FOLDER_NAME)
os.makedirs(review_path, exist_ok=True)
print(f"Review folder created: {review_path}")

moved_count = 0

for filename in os.listdir(DATASET_PATH):
    # Ensure we only check image files (you can add more extensions if necessary)
    if not (filename.lower().endswith(('.jpg', '.jpeg', '.png'))):
        continue

    # 1. Check for common keywords
    is_augmented = False
    name_parts = os.path.splitext(filename)[0].lower().split('_')

    for keyword in AUGMENTATION_KEYWORDS:
        if keyword in name_parts:
            is_augmented = True
            break
        # Also check for keywords in the full filename (e.g., "img-rotate-1.jpg")
        if keyword in filename.lower():
            is_augmented = True
            break

    # 2. Check for long random hashes
    if not is_augmented and HASH_PATTERN.search(filename):
        is_augmented = True

    # Move the file if it is flagged as augmented
    if is_augmented:
        source_file = os.path.join(DATASET_PATH, filename)
        destination_file = os.path.join(review_path, filename)
        shutil.move(source_file, destination_file)
        moved_count += 1

print("-" * 30)
print(f"✅ Script finished. {moved_count} potential augmented images moved to '{REVIEW_FOLDER_NAME}'.")
print("NEXT STEP: Review the files in the new folder and then upload the remaining cleaned dataset to Roboflow.")